on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

env:
  TF_IN_AUTOMATION: true
  MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}
  AWS_REGION: eu-west-2

permissions: {}

jobs:
  fetch-secrets:
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@3f4b0b80deea0ac74630e80189e1edeee3378793 # v6.1.5
    permissions:
      id-token: write
      contents: read
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}

  go-tests:
    permissions:
      id-token: write
      contents: read
      actions: write
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@3f4b0b80deea0ac74630e80189e1edeee3378793 # v6.1.5
        with:
          environment_management: ${{ needs.fetch-secrets.outputs.environment_management}}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Set Account Number
        run: |
          ACCOUNT_NUMBER=$(jq -r -e '.account_ids["testing-test"]' <<< "$ENVIRONMENT_MANAGEMENT")
          echo "::add-mask::$ACCOUNT_NUMBER"
          echo ACCOUNT_NUMBER=$ACCOUNT_NUMBER >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions-testing
          role-session-name: terratest-oidc
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26
          cache-dependency-path: "**/go.sum"
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ~1.3
          terraform_wrapper: false
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: |
          chmod 700 ../scripts/redact-output.sh
          go test -v | ../scripts/redact-output.sh
          exit ${PIPESTATUS[0]}
