on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

env:
  TF_IN_AUTOMATION: true
  MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}
  AWS_REGION: eu-west-2

permissions: {}

jobs:
  fetch-secrets:
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@5b44b387694dfa249cfa2dcf289ca871abe9e3e2 # v5.0.1
    permissions:
      id-token: write
      contents: read
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}

  go-tests:
    permissions:
      id-token: write
      contents: read
      actions: write
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@5b44b387694dfa249cfa2dcf289ca871abe9e3e2 # v5.0.1
        with:
          environment_management: ${{ needs.fetch-secrets.outputs.environment_management}}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Set Account Number
        run: |
          ACCOUNT_NUMBER=$(jq -r -e '.account_ids["testing-test"]' <<< "$ENVIRONMENT_MANAGEMENT")
          echo "::add-mask::$ACCOUNT_NUMBER"
          echo ACCOUNT_NUMBER=$ACCOUNT_NUMBER >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions-testing
          role-session-name: terratest-oidc
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.26
          cache-dependency-path: "**/go.sum"
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ~1.3
          terraform_wrapper: false
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: |
          chmod 700 ../scripts/redact-output.sh
          go test -v | ../scripts/redact-output.sh
          exit ${PIPESTATUS[0]}
